In [ ]:
# One dimensional array

In [5]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
for i in arr:
    print(arr[i])


0
1
2
3
4
5
6
7
8
9


In [28]:
for i in arr:
    if arr[i] <= 4:
        print(arr[i])

0
1
2
3
4


In [24]:
print(arr[0:3])
print(arr[0:3, ]) # Printing row from 0 to 3 but no column.
print(arr[1])     # printing second column but zero row
print(arr[0: ])   # Printing first row and zero column

[0 1 2]
[0 1 2]
1
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Two Dimensional Array

In [33]:
arr1 = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [39]:
# Accessing array elements via loop
arr1 = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])
rows, col = arr1.shape

for i in range(rows):
    for j in range(col):
        print(f"Element at ({i},{j}) = ", arr1[i][j])

Element at (0,0) =  1
Element at (0,1) =  2
Element at (0,2) =  3
Element at (0,3) =  4
Element at (0,4) =  5
Element at (1,0) =  6
Element at (1,1) =  7
Element at (1,2) =  8
Element at (1,3) =  9
Element at (1,4) =  10


In [111]:
print("1. Printing first row:\n",arr1[0],"\n") 
print("2. Printing second row:\n",arr1[1],"\n")

print("3. Printing all row upto 1(not included 1) and all columns:\n",arr1[0:1],"\n") 
print("4. Printing all rows from 0 to above:\n",arr1[0: ],"\n") 
print("5. Printing all rows from 1 to above:\n",arr1[1:],"\n") 

print("6. Printing rows and columns from 0 to above:\n",arr1[0: , 0:],"\n")
print("7. Printing all rows and 3 columns:\n",arr1[0: , 0:3],"\n")
print("8. Printing first row and 3 columns:\n",arr1[0, 0:3],"\n") 
print("9. Printing first row and all columns:\n",arr1[0, 0:],"\n") 
print("10. Printing second row and 5 columns:\n",arr1[1, 0:5],"\n") 



print("11. Printing 0 to above all rows and all columns:\n",arr1[0:, ],"\n") 
print("12. Printing 0 to above all rows and 3rd and 4th column:\n",arr1[0:, 2:4 ],"\n") 

print("13. Remove last row and last column:\n", arr1[:-1 , :-1], "\n")
print("14. Print all rows and remove last column:\n", arr1[ : , :-1], "\n")
print("14. Remove all rows and print last column means nothing or empty:\n", arr1[ :-2 , 4], "\n")
print("14. Remove one row from last or end and print 5th column:\n", arr1[ :-1 , 4], "\n")

1. Printing first row:
 [1 2 3 4 5] 

2. Printing second row:
 [ 6  7  8  9 10] 

3. Printing all row upto 1(not included 1) and all columns:
 [[1 2 3 4 5]] 

4. Printing all rows from 0 to above:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

5. Printing all rows from 1 to above:
 [[ 6  7  8  9 10]] 

6. Printing rows and columns from 0 to above:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

7. Printing all rows and 3 columns:
 [[1 2 3]
 [6 7 8]] 

8. Printing first row and 3 columns:
 [1 2 3] 

9. Printing first row and all columns:
 [1 2 3 4 5] 

10. Printing second row and 5 columns:
 [ 6  7  8  9 10] 

11. Printing 0 to above all rows and all columns:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

12. Printing 0 to above all rows and 3rd and 4th column:
 [[3 4]
 [8 9]] 

13. Remove last row and last column:
 [[1 2 3 4]] 

14. Print all rows and remove last column:
 [[1 2 3 4]
 [6 7 8 9]] 

14. Remove all rows and print last column means nothing or empty:
 [] 

14. Remove one row from last or end and 

In [ ]:
# Broadcasting in Numpy

In [114]:
matrix4_3 = np.array([
                [0, 0, 0],
                [10, 10, 10],
                [20, 20, 20],
                [30, 30, 30]])

matrixx4_3 = np.array([
                [0, 1, 2],
                [0, 1, 2],
                [0, 1, 2],
                [0, 1, 2]])

print("Sum of matrix4_3 + matrixx4_3:\n", matrix4_3 + matrixx4_3)

Sum of matrix4_3 + matrixx4_3:
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [115]:
matrix1_3 = np.array(
                [0, 1, 2])
print("Sum of matrix4_3 + matrix1_3:\n", matrix4_3 + matrix1_3)

Sum of matrix4_3 + matrix1_3:
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [116]:
matrix4_1 = np.array([
                [0],
                [10],
                [20],
                [30]])
print("Sum of matrix4_1 + matrix1_3:\n", matrix4_1 + matrix1_3)

Sum of matrix4_1 + matrix1_3:
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
# Shape of the matrix

In [120]:
matrix = np.array([
                 [0,  1,  2],
                 [10, 11, 12],
                 [20, 21, 22],
                 [30, 31, 32]])
print("The shape of the matrix is: ", matrix.shape)

The shape of the matrix is:  (4, 3)


In [ ]:
# Reshaping the matrix
### Matrix can be reshaped to any shape that is consistent with the data size

In [125]:
new_matrix = matrix.reshape(2,6)
new_matrix1 = matrix.reshape(3,4)

print("Reshaped matrix4_3 into matrix2_6:\n", new_matrix)
print("Reshaped matrix4_3 into matrix3_4:\n", new_matrix1)

Reshaped matrix4_3 into matrix2_6:
 [[ 0  1  2 10 11 12]
 [20 21 22 30 31 32]]
Reshaped matrix4_3 into matrix3_4:
 [[ 0  1  2 10]
 [11 12 20 21]
 [22 30 31 32]]


In [ ]:
# Transpose of Matrix

In [132]:
transpose_matrix = new_matrix.T

print("new_matrix is:\n", new_matrix)
print("Shape of the new_matrix is:\n", new_matrix.shape, "\n")
print("Transpose of new_matrix is:\n", transpose_matrix)
print("Shape of the transpose_matrix:\n", transpose_matrix.shape)

new_matrix is:
 [[ 0  1  2 10 11 12]
 [20 21 22 30 31 32]]
Shape of the new_matrix is:
 (2, 6) 

Transpose of new_matrix is:
 [[ 0 20]
 [ 1 21]
 [ 2 22]
 [10 30]
 [11 31]
 [12 32]]
Shape of the transpose_matrix:
 (6, 2)


In [ ]:
# Diagonal Matrices

In [135]:
diag = np.diag([1,2,3,4,5])
print("Diagonal matrix of the 1-d array is:\n", diag)

Diagonal matrix of the 1-d array is:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
# Indentity Matrices

In [137]:
# A 10 * 10 matrix with ones at diagonal and rest are zeros
identity = np.identity(10)
print("Identity matrix is:\n", identity)

Identity matrix is:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
# Arrays of random numbers or sequences

In [139]:
# Creating a random array, starting from 5, with a step of 5 and ending at 100.
seq = np.arange(start = 0, stop = 100, step = 5)
print("Random Array:\n", seq)

Random Array:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
# One-Dimensional random Vector

In [141]:
rand_1d_vector = np.random.rand(10)
print("One-Dimensional random vector:\n", rand_1d_vector)

One-Dimensional random vector:
 [0.81149304 0.76611955 0.86544247 0.92211424 0.45072375 0.92886791
 0.47642147 0.76753489 0.34329791 0.37107317]


In [ ]:
# Two-Dimensional random Vector

In [143]:
rand_2d_vector = np.random.rand(10, 10)
print("Two-Dimensional random vector:\n", rand_2d_vector)

Two-Dimensional random vector:
 [[0.44877786 0.79773685 0.65423428 0.07002123 0.77812458 0.74285224
  0.09307951 0.83522991 0.42794147 0.39872276]
 [0.75020515 0.4947253  0.61080779 0.77596738 0.24284791 0.76576027
  0.74196756 0.06880805 0.24179253 0.29798927]
 [0.6468812  0.39994207 0.48840111 0.57694265 0.57677969 0.18641002
  0.83511563 0.41949157 0.38872066 0.62161858]
 [0.09630446 0.15696254 0.43571831 0.28991476 0.3280421  0.284879
  0.63085827 0.52117619 0.76063122 0.01531273]
 [0.79729004 0.73288946 0.6640342  0.89654991 0.45156364 0.65005407
  0.27087288 0.27819332 0.7983602  0.33568873]
 [0.8759933  0.90788096 0.60859991 0.31062405 0.53919806 0.11335634
  0.25622879 0.5302027  0.14464378 0.99359039]
 [0.61752184 0.86467987 0.99519105 0.21908507 0.84414157 0.39727712
  0.97074351 0.15839896 0.16142972 0.82449265]
 [0.15656922 0.64078349 0.58169819 0.19586627 0.05599648 0.64293591
  0.10165978 0.55359997 0.15750069 0.60928962]
 [0.39990649 0.74437274 0.33754749 0.39955327 0.90

In [ ]:
# Min-Max and Index of Min-Max

In [146]:
my_matrix = np.array([1,2,3,4,5,6,7,8,9,10])
print("The max is {} at index {}".format(my_matrix.max(), my_matrix.argmax()))
print("The min is {} at index {}".format(my_matrix.min(), my_matrix.argmin()))

The max is 10 at index 9
The min is 1 at index 0


In [ ]:
# Dot Product of matrices in seconds

In [148]:
import time
my_matrix = np.random.rand(1000,1000)
my_matrix1 = np.random.rand(1000, 1000)

start = time.time()
# Make sure that dimensions should be agree!
dot_product = my_matrix.dot(my_matrix1)
end = time.time()

print("It took {} seconds to calculate the dot product!".format(round(end-start, 4)))

It took 0.0372 seconds to calculate the dot product!


In [ ]:
# Linear Algebra

In [ ]:
# Determinent of a Matrix

In [173]:
import numpy.linalg as la
my_matrix = np.array([
                [5, 5, 5, 5],
                [10, 10, 16, 10],
                [20, 15, 20, 20],
                [30, 25, 30, 40]])
det = la.det(my_matrix)
print("The determinant of my_matrix is:\n", det)

The determinant of my_matrix is:
 1499.9999999999986


In [ ]:
# Inverse of a matrix
## Inverse = adj(matrix)/det(matrix)
## Note: Make sure its SINGULAR

In [157]:
inv = la.inv(my_matrix)
print("The Inverse of my_matrix is:\n", inv)

The Inverse of my_matrix is:
 [[-6.66666667e-02 -1.66666667e-01  3.00000000e-01 -1.00000000e-01]
 [ 8.00000000e-01 -6.66133815e-17 -2.00000000e-01  9.99200722e-17]
 [-3.33333333e-01  1.66666667e-01  0.00000000e+00 -3.70074342e-17]
 [-2.00000000e-01 -3.33066907e-17 -1.00000000e-01  1.00000000e-01]]


In [ ]:
# Calculate eigen values
## NOTE: make sure the matrix is SQUARE [eigen values do not exit for matrix whose dimensions are mxn where m!=n]!

In [165]:
eigen_values, eigen_vectors = la.eig(my_matrix)
print("The eigen values are:\n", eigen_values, "\n")
print("The eigen vectors are:\n", eigen_vectors, "\n")

The eigen values are:
 [69.85210005+0.j         -0.29132439+1.91374116j -0.29132439-1.91374116j
  5.73054872+0.j        ] 

The eigen vectors are:
 [[-0.12174611+0.j          0.15379405+0.41454187j  0.15379405-0.41454187j
  -0.17947102+0.j        ]
 [-0.28357858+0.j         -0.76794736+0.j         -0.76794736-0.j
  -0.5803796 +0.j        ]
 [-0.46668595+0.j          0.31666357-0.30279403j  0.31666357+0.30279403j
  -0.21149313+0.j        ]
 [-0.8288337 +0.j          0.12986378-0.07703668j  0.12986378+0.07703668j
   0.76565026+0.j        ]] 



In [ ]:
# Cholesky factorization. 
## NOTE: make sure matrix is Positive Definite!

In [168]:
my_matrix1 = np.array([
                [4, 1, 1],
                [1, 3, 0],
                [1, 0, 2]])

cholesky = la.cholesky(my_matrix1)
print("The Cholesky factorization of my_matrix1 is:\n", cholesky)

The Cholesky factorization of my_matrix1 is:
 [[ 2.          0.          0.        ]
 [ 0.5         1.6583124   0.        ]
 [ 0.5        -0.15075567  1.31425748]]


In [ ]:
# Rank of a matrix. 
## Rank of a matrix is the number of linearly independent columns/rows in a matrix.

In [172]:
rank = la.matrix_rank(my_matrix)
rank1 = la.matrix_rank(my_matrix1)

print("The rank of my_matrix is:\n", rank)
print("The rank of my_matrix1 is:\n", rank1)

The rank of my_matrix is:
 4
The rank of my_matrix1 is:
 3


In [ ]:
# Numpy Exercise

In [ ]:
# 1. Write a NumPy program to extract upper triangular part of a NumPy matrix.

In [177]:
exercise_matrix = np.array([
    [6, 2, 1, 1],
    [2, 5, 2, 1],
    [1, 2, 4, 1],
    [1, 1, 1, 3]
])
# Upper Triangle part
upper_triangle = np.triu(exercise_matrix)
print("The Upper Triangle of the exercise_matrix is:\n", upper_triangle, "\n")

# Lower Triangle part
lower_triangle = np.tril(exercise_matrix)
print("The Lower Triangle of the exercise_matrix is:\n", lower_triangle)

The Upper Triangle of the exercise_matrix is:
 [[6 2 1 1]
 [0 5 2 1]
 [0 0 4 1]
 [0 0 0 3]] 

The Lower Triangle of the exercise_matrix is:
 [[6 0 0 0]
 [2 5 0 0]
 [1 2 4 0]
 [1 1 1 3]]


In [ ]:
# 2. Write a NumPy program to extract all the elements of the second and third columns from a given (4x4) my_array.

In [179]:
print("The elements of second and third columns are:\n", exercise_matrix[0: , 1:3])

The elements of second and third columns are:
 [[2 1]
 [5 2]
 [2 4]
 [1 1]]


In [ ]:
# 3. Write a NumPy program to count the occurrence of a specified item in a given NumPy my_array.

In [184]:
# By .count_nonzero() method
count_1 = np.count_nonzero(exercise_matrix == 2)
print("The occurence of 2 inside exercixe_matrix by count() method is:\n", count_1, "\n")

# By .sum() method
count_2 = (exercise_matrix == 2).sum()
print("The occurence of 2 inside exercixe_matrix by sum() method is:\n", count_2)

The occurence of 2 inside exercixe_matrix by count() method is:
 4 

The occurence of 2 inside exercixe_matrix by sum() method is:
 4


In [ ]:
# 4.Write a NumPy program to sum and compute the product of a NumPy my_array elements.

In [189]:
# Sum of matrix elements
sum = np.sum(exercise_matrix)
print("The sum of elements inside the exercise_matrix is:\n", sum, "\n")

# Product of matrix elements
product = np.prod(exercise_matrix)
print("The product of elements inside the exercise_matrix is:\n", product)

The sum of elements inside the exercise_matrix is:
 34 

The product of elements inside the exercise_matrix is:
 5760
