# 1 NumPy Module

- Computers make it very easy to perform complex computations in a matter of seconds.  
- Python has a dedicated library for numeric computation known as **NumPy**.  
- The applications of NumPy are diverse, but here we will focus on **matrix multiplication**.  
- At the base of it all, it uses the `numpy.ndarray` data type that can function as a vector or matrix of any dimension.  
- Once your data is in the `ndarray` form, you can perform a multitude of operations on it.  

---

#### Exploring NumPy Arrays

- Before we move further, let’s have a look at **NumPy arrays** first.  
- NumPy arrays are very similar to lists but have additional operations such as:  
  - **Multi-indexing**: lets you slice and subset with respect to rows and columns.  

##### Array Indexing & Slicing in NumPy

| Operator        | Description                                    |
|-----------------|------------------------------------------------|
| `my_array[i]`   | 1D array element at index `i`                  |
| `my_array[i, j]`| 2D array element at row `i`, column `j`        |
| `my_array[i<4]` | Boolean indexing (e.g., values less than 4)    |
| `my_array[0:3]` | Select items of index 0, 1, and 2              |
| `my_array[0:2,1]` | Select items of rows 0 and 1 at column 1     |
| `my_array[:1]`  | Select items of row 0 (`my_array[0:1, :]`)     |
| `my_array[1:2, :]` | Select items of row 1                       |
| `my_array[::-1]`| Reverse the array                              |

---

## 1.1 One dimensional Numpy Array

In [1]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
# Accessing the array elements via loop
for i in arr:
    print(arr[i])

0
1
2
3
4
5
6
7
8
9


In [3]:
for i in arr:
    if arr[i] <= 4:
        print(arr[i])

0
1
2
3
4


In [4]:
print(arr[0:3])
print(arr[0:3, ]) # Printing row from 0 to 3 but no column.
print(arr[1])     # printing second column but zero row
print(arr[0: ])   # Printing first row and zero column

[0 1 2]
[0 1 2]
1
[0 1 2 3 4 5 6 7 8 9]


## 1.2. Two Dimensional Numpy Array

In [5]:
arr1 = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
# Accessing array elements via loop
arr1 = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])
rows, col = arr1.shape

for i in range(rows):
    for j in range(col):
        print(f"Element at ({i},{j}) = ", arr1[i][j])

Element at (0,0) =  1
Element at (0,1) =  2
Element at (0,2) =  3
Element at (0,3) =  4
Element at (0,4) =  5
Element at (1,0) =  6
Element at (1,1) =  7
Element at (1,2) =  8
Element at (1,3) =  9
Element at (1,4) =  10


In [7]:
print("1. Printing first row:\n",arr1[0],"\n") 
print("2. Printing second row:\n",arr1[1],"\n")

print("3. Printing all row upto 1(not included 1) and all columns:\n",arr1[0:1],"\n") 
print("4. Printing all rows from 0 to above:\n",arr1[0: ],"\n") 
print("5. Printing all rows from 1 to above:\n",arr1[1:],"\n") 

print("6. Printing rows and columns from 0 to above:\n",arr1[0: , 0:],"\n")
print("7. Printing all rows and 3 columns:\n",arr1[0: , 0:3],"\n")
print("8. Printing first row and 3 columns:\n",arr1[0, 0:3],"\n") 
print("9. Printing first row and all columns:\n",arr1[0, 0:],"\n") 
print("10. Printing second row and 5 columns:\n",arr1[1, 0:5],"\n") 



print("11. Printing 0 to above all rows and all columns:\n",arr1[0:, ],"\n") 
print("12. Printing 0 to above all rows and 3rd and 4th column:\n",arr1[0:, 2:4 ],"\n") 

print("13. Remove last row and last column:\n", arr1[:-1 , :-1], "\n")
print("14. Print all rows and remove last column:\n", arr1[ : , :-1], "\n")
print("14. Remove all rows and print last column means nothing or empty:\n", arr1[ :-2 , 4], "\n")
print("14. Remove one row from last or end and print 5th column:\n", arr1[ :-1 , 4], "\n")

1. Printing first row:
 [1 2 3 4 5] 

2. Printing second row:
 [ 6  7  8  9 10] 

3. Printing all row upto 1(not included 1) and all columns:
 [[1 2 3 4 5]] 

4. Printing all rows from 0 to above:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

5. Printing all rows from 1 to above:
 [[ 6  7  8  9 10]] 

6. Printing rows and columns from 0 to above:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

7. Printing all rows and 3 columns:
 [[1 2 3]
 [6 7 8]] 

8. Printing first row and 3 columns:
 [1 2 3] 

9. Printing first row and all columns:
 [1 2 3 4 5] 

10. Printing second row and 5 columns:
 [ 6  7  8  9 10] 

11. Printing 0 to above all rows and all columns:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

12. Printing 0 to above all rows and 3rd and 4th column:
 [[3 4]
 [8 9]] 

13. Remove last row and last column:
 [[1 2 3 4]] 

14. Print all rows and remove last column:
 [[1 2 3 4]
 [6 7 8 9]] 

14. Remove all rows and print last column means nothing or empty:
 [] 

14. Remove one row from last or end and 

## 1.3 Broadcasting in Arrays (Python – NumPy)

##### Definition
**Broadcasting** is the ability of NumPy to perform arithmetic operations on arrays of different shapes by automatically stretching (broadcasting) the smaller array to match the shape of the larger one without actually copying data.  

- Makes array operations **fast** and **memory efficient**.  
- If two arrays are of the same size, arithmetic operations occur **element-wise**.  


In [8]:
# Example 1
matrix4_3 = np.array([
                [0, 0, 0],
                [10, 10, 10],
                [20, 20, 20],
                [30, 30, 30]])

matrixx4_3 = np.array([
                [0, 1, 2],
                [0, 1, 2],
                [0, 1, 2],
                [0, 1, 2]])

print("Sum of matrix4_3 + matrixx4_3:\n", matrix4_3 + matrixx4_3)

Sum of matrix4_3 + matrixx4_3:
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [9]:
# Example 2
matrix1_3 = np.array(
                [0, 1, 2])
print("Sum of matrix4_3 + matrix1_3:\n", matrix4_3 + matrix1_3)

Sum of matrix4_3 + matrix1_3:
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [10]:
# Example 3
matrix4_1 = np.array([
                [0],
                [10],
                [20],
                [30]])
print("Sum of matrix4_1 + matrix1_3:\n", matrix4_1 + matrix1_3)

Sum of matrix4_1 + matrix1_3:
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


## 1.4. Basic NumPy Operations

We can perform several useful operations on NumPy arrays such as:

1. Creating random sequences  
2. Creating patterned sequences  
3. Creating 1D and 2D arrays  
4. Finding minimum and maximum values  
5. Finding indices of minimum and maximum values  
6. Creating identity and diagonal matrices  
7. Performing transpose and dot products  

### 1.4.1 Shape of the matrix

In [11]:
matrix = np.array([
                 [0,  1,  2],
                 [10, 11, 12],
                 [20, 21, 22],
                 [30, 31, 32]])
print("The shape of the matrix is: ", matrix.shape)

The shape of the matrix is:  (4, 3)


### 1.4.2 Reshaping the matrix
##### Matrix can be reshaped to any shape that is consistent with the data size

In [12]:
new_matrix = matrix.reshape(2,6)
new_matrix1 = matrix.reshape(3,4)

print("Reshaped matrix4_3 into matrix2_6:\n", new_matrix)
print("Reshaped matrix4_3 into matrix3_4:\n", new_matrix1)

Reshaped matrix4_3 into matrix2_6:
 [[ 0  1  2 10 11 12]
 [20 21 22 30 31 32]]
Reshaped matrix4_3 into matrix3_4:
 [[ 0  1  2 10]
 [11 12 20 21]
 [22 30 31 32]]


### 1.4.3 Transpose of Matrix

In [13]:
transpose_matrix = new_matrix.T

print("new_matrix is:\n", new_matrix)
print("Shape of the new_matrix is:\n", new_matrix.shape, "\n")
print("Transpose of new_matrix is:\n", transpose_matrix)
print("Shape of the transpose_matrix:\n", transpose_matrix.shape)

new_matrix is:
 [[ 0  1  2 10 11 12]
 [20 21 22 30 31 32]]
Shape of the new_matrix is:
 (2, 6) 

Transpose of new_matrix is:
 [[ 0 20]
 [ 1 21]
 [ 2 22]
 [10 30]
 [11 31]
 [12 32]]
Shape of the transpose_matrix:
 (6, 2)


### 1.4.4 Diagonal Matrices

In [14]:
diag = np.diag([1,2,3,4,5])
print("Diagonal matrix of the 1-d array is:\n", diag)

Diagonal matrix of the 1-d array is:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### 1.4.5 Indentity Matrices

In [15]:
# A 10 * 10 matrix with ones at diagonal and rest are zeros
identity = np.identity(10)
print("Identity matrix is:\n", identity)

Identity matrix is:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### 1.4.6 Arrays of random numbers or sequences

In [16]:
# Creating a random array, starting from 5, with a step of 5 and ending at 100.
seq = np.arange(start = 0, stop = 100, step = 5)
print("Random Array:\n", seq)

Random Array:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


### 1.4.7 One-Dimensional random Vector

In [17]:
rand_1d_vector = np.random.rand(10)
print("One-Dimensional random vector:\n", rand_1d_vector)

One-Dimensional random vector:
 [0.69420432 0.4791952  0.62313177 0.54014949 0.58871817 0.00364749
 0.70537882 0.3779039  0.14606241 0.22808252]


### 1.4.8 Two-Dimensional random Vector

In [18]:
rand_2d_vector = np.random.rand(10, 10)
print("Two-Dimensional random vector:\n", rand_2d_vector)

Two-Dimensional random vector:
 [[0.27333747 0.18499486 0.52369453 0.45194676 0.45722778 0.34044445
  0.40314545 0.6479299  0.71395017 0.32113309]
 [0.08460509 0.70304351 0.56628909 0.03639312 0.67351781 0.86344901
  0.37294461 0.70093306 0.75800938 0.53361779]
 [0.13974946 0.40603329 0.31771239 0.61118614 0.211458   0.1267857
  0.63125707 0.82401444 0.47376896 0.89701251]
 [0.25600587 0.42744626 0.65850076 0.10639028 0.1532328  0.16233029
  0.35766184 0.96190756 0.99455604 0.20292164]
 [0.28640094 0.50777923 0.2446217  0.77653018 0.84427869 0.45749655
  0.01561827 0.01516191 0.44164842 0.87823   ]
 [0.1271288  0.72719945 0.18046294 0.5835891  0.34820734 0.84364175
  0.4000404  0.60428856 0.40137252 0.17023808]
 [0.96174529 0.66475848 0.947169   0.73098777 0.69586614 0.15577084
  0.46618842 0.18270348 0.52301841 0.52495263]
 [0.06859957 0.63258    0.4508505  0.6339283  0.43475939 0.14949913
  0.87226199 0.18766032 0.93505854 0.51938445]
 [0.39987405 0.90155378 0.1405646  0.88738658 0.3

### 1.4.9 Min-Max and Index of Min-Max

In [19]:
my_matrix = np.array([1,2,3,4,5,6,7,8,9,10])
print("The max is {} at index {}".format(my_matrix.max(), my_matrix.argmax()))
print("The min is {} at index {}".format(my_matrix.min(), my_matrix.argmin()))

The max is 10 at index 9
The min is 1 at index 0


### 1.4.10 Dot Product of matrices in seconds

In [20]:
import time
my_matrix = np.random.rand(1000,1000)
my_matrix1 = np.random.rand(1000, 1000)

start = time.time()
# Make sure that dimensions should be agree!
dot_product = my_matrix.dot(my_matrix1)
end = time.time()

print("It took {} seconds to calculate the dot product!".format(round(end-start, 4)))

It took 0.0248 seconds to calculate the dot product!


## 1.5 Linear Algebra with NumPy

Within NumPy, there is a **sub-module `linalg`** (short for *linear algebra*) that contains commonly used functions:

- Determinant of a matrix  
- Inverse of a matrix  
- Cholesky factorization of a matrix  
- Eigenvalues of a matrix  
- Rank of a matrix  


### 1.5.1 Determinent of a Matrix

In [21]:
import numpy.linalg as la
my_matrix = np.array([
                [5, 5, 5, 5],
                [10, 10, 16, 10],
                [20, 15, 20, 20],
                [30, 25, 30, 40]])
det = la.det(my_matrix)
print("The determinant of my_matrix is:\n", det)

The determinant of my_matrix is:
 1499.9999999999986


### 1.5.2 Inverse of a matrix
##### Inverse = adj(matrix)/det(matrix)
##### Note: Make sure its SINGULAR

In [22]:
inv = la.inv(my_matrix)
print("The Inverse of my_matrix is:\n", inv)

The Inverse of my_matrix is:
 [[-6.66666667e-02 -1.66666667e-01  3.00000000e-01 -1.00000000e-01]
 [ 8.00000000e-01 -6.66133815e-17 -2.00000000e-01  9.99200722e-17]
 [-3.33333333e-01  1.66666667e-01  0.00000000e+00 -3.70074342e-17]
 [-2.00000000e-01 -3.33066907e-17 -1.00000000e-01  1.00000000e-01]]


### 1.5.3 Calculate eigen values
##### NOTE: make sure the matrix is SQUARE [eigen values do not exit for matrix whose dimensions are mxn where m!=n]!

In [23]:
eigen_values, eigen_vectors = la.eig(my_matrix)
print("The eigen values are:\n", eigen_values, "\n")
print("The eigen vectors are:\n", eigen_vectors, "\n")

The eigen values are:
 [69.85210005+0.j         -0.29132439+1.91374116j -0.29132439-1.91374116j
  5.73054872+0.j        ] 

The eigen vectors are:
 [[-0.12174611+0.j          0.15379405+0.41454187j  0.15379405-0.41454187j
  -0.17947102+0.j        ]
 [-0.28357858+0.j         -0.76794736+0.j         -0.76794736-0.j
  -0.5803796 +0.j        ]
 [-0.46668595+0.j          0.31666357-0.30279403j  0.31666357+0.30279403j
  -0.21149313+0.j        ]
 [-0.8288337 +0.j          0.12986378-0.07703668j  0.12986378+0.07703668j
   0.76565026+0.j        ]] 



### 1.5.4 Cholesky factorization. 
##### NOTE: make sure matrix is Positive Definite!

In [24]:
my_matrix1 = np.array([
                [4, 1, 1],
                [1, 3, 0],
                [1, 0, 2]])

cholesky = la.cholesky(my_matrix1)
print("The Cholesky factorization of my_matrix1 is:\n", cholesky)

The Cholesky factorization of my_matrix1 is:
 [[ 2.          0.          0.        ]
 [ 0.5         1.6583124   0.        ]
 [ 0.5        -0.15075567  1.31425748]]


### 1.5.5 Rank of a matrix. 
##### Rank of a matrix is the number of linearly independent columns/rows in a matrix.

In [25]:
rank = la.matrix_rank(my_matrix)
rank1 = la.matrix_rank(my_matrix1)

print("The rank of my_matrix is:\n", rank)
print("The rank of my_matrix1 is:\n", rank1)

The rank of my_matrix is:
 4
The rank of my_matrix1 is:
 3


## 1.6 Numpy Exercise

### 1.6.1 Write a NumPy program to extract upper triangular part of a NumPy matrix.

In [26]:
exercise_matrix = np.array([
    [6, 2, 1, 1],
    [2, 5, 2, 1],
    [1, 2, 4, 1],
    [1, 1, 1, 3]
])
# Upper Triangle part
upper_triangle = np.triu(exercise_matrix)
print("The Upper Triangle of the exercise_matrix is:\n", upper_triangle, "\n")

# Lower Triangle part
lower_triangle = np.tril(exercise_matrix)
print("The Lower Triangle of the exercise_matrix is:\n", lower_triangle)

The Upper Triangle of the exercise_matrix is:
 [[6 2 1 1]
 [0 5 2 1]
 [0 0 4 1]
 [0 0 0 3]] 

The Lower Triangle of the exercise_matrix is:
 [[6 0 0 0]
 [2 5 0 0]
 [1 2 4 0]
 [1 1 1 3]]


### 1.6.2 Write a NumPy program to extract all the elements of the second and third columns from a given (4x4) my_array.

In [27]:
print("The elements of second and third columns are:\n", exercise_matrix[0: , 1:3])

The elements of second and third columns are:
 [[2 1]
 [5 2]
 [2 4]
 [1 1]]


### 1.6.3 Write a NumPy program to count the occurrence of a specified item in a given NumPy my_array.

In [28]:
# By .count_nonzero() method
count_1 = np.count_nonzero(exercise_matrix == 2)
print("The occurence of 2 inside exercixe_matrix by count() method is:\n", count_1, "\n")

# By .sum() method
count_2 = (exercise_matrix == 2).sum()
print("The occurence of 2 inside exercixe_matrix by sum() method is:\n", count_2)

The occurence of 2 inside exercixe_matrix by count() method is:
 4 

The occurence of 2 inside exercixe_matrix by sum() method is:
 4


### 1.6.4 Write a NumPy program to sum and compute the product of a NumPy my_array elements.

In [29]:
# Sum of matrix elements
sum = np.sum(exercise_matrix)
print("The sum of elements inside the exercise_matrix is:\n", sum, "\n")

# Product of matrix elements
product = np.prod(exercise_matrix)
print("The product of elements inside the exercise_matrix is:\n", product)

The sum of elements inside the exercise_matrix is:
 34 

The product of elements inside the exercise_matrix is:
 5760


#Recap

- Installing Modules  
- Parsing XML with LXML  
- Config Parser  
- Threading  
- NumPy  
